import { StyleSheet } from "react-native";

const conteudoStyle = StyleSheet.create({
    // ========== ESTILOS EXISTENTES ==========
    titulo: {
        color: "#bfc0d1",
        alignSelf: 'center',
        fontSize: 24,
        fontWeight: 'bold',
        margin: 10,
        textAlign: 'center',
        fontFamily: 'Roboto-Bold',
    },
    subtitulo: {
        color: "#bfc0d1",
        alignSelf: 'center',
        fontSize: 20,
        fontFamily: 'Roboto-Medium',
    },
    textoBotao: {
        color: "#fff",
        alignSelf: 'center',
        fontSize: 16,
        textAlign: 'center',
        fontFamily: 'Roboto-Medium',
    },
    conteudo: {
        left: 0,
        right: 0,
        bottom: 0,
        top: 0,
        width: "100%",
        height: "100%",
        paddingHorizontal: 10,
        paddingBottom: 10,
    },
    cardProgresso: {
        backgroundColor: '#212636',
        borderWidth: 1,
        borderColor: '#2e354d',
        width: "80%",
        maxWidth: 600,
        alignSelf: 'center',
        borderRadius: 15,
        paddingHorizontal: 15,
        paddingVertical: 10,
        marginTop: 25,
    },
    cardSugestao: {
        backgroundColor: '#212636',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 20,
        width: '85%',
        maxWidth: 600,
        borderWidth: 2,
        borderRadius: 10,
        borderColor: '#2e354d',
    },
    botao: {
        width: "60%",
        maxWidth: 250,
        borderWidth: 2,
        borderColor: '#836fd1',
        backgroundColor: '#60519b',
        borderRadius: 5,
        margin: 5,
        padding: 10,
        alignSelf: "center",
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        fontFamily: 'Roboto-Medium',
    },
    barraFundo: {
        height: 20,
        width: '100%',
        maxWidth: 400,
        alignSelf: 'center',
        marginVertical: 15,
        backgroundColor: '#314',
        borderRadius: 10,
        overflow: 'hidden',
        borderWidth: 2,
        borderColor: '#416',
    },
    barraPreenchida: {
        height: '100%',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#734',
    },
    textoPorcentagem: {
        fontSize: 16,
        color: '#fff',
        alignSelf: 'center',
        textAlign: 'center',
        fontFamily: 'Roboto-Regular',
    },
    hudContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        backgroundColor: '#212636',
        borderBottomWidth: 2,
        borderBottomColor: '#2e354d',
        paddingVertical: 12,
        paddingHorizontal: 10,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 5,
    },
    hudItem: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        paddingHorizontal: 8,
    },
    hudIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 8,
        backgroundColor: '#1a1f2e',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
        borderWidth: 1,
        borderColor: '#2e354d',
    },
    hudContent: {
        flex: 1,
    },
    hudLabel: {
        color: '#9ca3af',
        fontSize: 12,
        fontWeight: '600',
        marginBottom: 2,
        fontFamily: 'Roboto-Medium',
    },
    hudValue: {
        color: '#bfc0d1',
        fontSize: 16,
        fontWeight: 'bold',
        fontFamily: 'Roboto-Bold',
    },
    hudDivider: {
        width: 1,
        height: 30,
        backgroundColor: '#2e354d',
        marginHorizontal: 8,
    },
    secaoFixaCursos: {
        backgroundColor: '#1c202c',
        paddingHorizontal: 10,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#2e354d',
    },
    inputBusca: {
        borderWidth: 1,
        borderColor: '#60519b',
        backgroundColor: '#0c101c',
        borderRadius: 8,
        marginHorizontal: 0,
        marginVertical: 15,
        paddingHorizontal: 15,
        paddingVertical: 12,
        color: '#bfc0d1',
        fontSize: 16,
        fontFamily: 'Roboto-Regular',
    },
    filtrosContainer: {
        marginHorizontal: -10,
        marginBottom: 0,
        maxHeight: 50,
        paddingHorizontal: 10,
    },
    botaoFiltro: {
        borderWidth: 1,
        borderColor: '#60519b',
        backgroundColor: 'transparent',
        borderRadius: 20,
        paddingHorizontal: 15,
        paddingVertical: 8,
        marginRight: 10,
    },
    botaoFiltroAtivo: {
        backgroundColor: '#60519b',
        borderColor: '#836fd1',
    },
    textoBotaoFiltro: {
        color: '#bfc0d1',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Roboto-Medium',
    },
    textoBotaoFiltroAtivo: {
        color: '#fff',
    },
    secaoScrollCursos: {
        flex: 1,
        backgroundColor: '#1c202c',
        paddingHorizontal: 10,
    },
    cardCurso: {
        backgroundColor: '#212636',
        borderWidth: 1,
        borderColor: '#2e354d',
        borderRadius: 12,
        paddingHorizontal: 15,
        paddingVertical: 15,
        marginHorizontal: 0,
        marginVertical: 10,
    },
    cardCursoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    categoriaBadge: {
        backgroundColor: '#60519b',
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 15,
        fontFamily: 'Roboto-Bold',
    },
    aulasTexto: {
        color: '#836fd1',
        fontSize: 12,
        fontWeight: '600',
        fontFamily: 'Roboto-Medium',
    },
    cardCursoTitulo: {
        color: '#bfc0d1',
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 8,
        fontFamily: 'Roboto-Bold',
    },
    cardCursoDescricao: {
        color: '#9ca3af',
        fontSize: 14,
        lineHeight: 20,
        marginBottom: 12,
        fontFamily: 'Roboto-Regular',
    },
    botaoContinuar: {
        borderColor: '#836fd1',
        backgroundColor: '#7c1272',
    },
    cardPerfil: {
        backgroundColor: '#212636',
        borderWidth: 1,
        borderColor: '#2e354d',
        borderRadius: 15,
        paddingHorizontal: 20,
        paddingVertical: 25,
        marginHorizontal: 10,
        marginVertical: 15,
        alignItems: 'center',
    },
    avatarContainer: {
        marginBottom: 20,
    },
    avatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#1a1f2e',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: '#60519b',
    },
    secaoInfo: {
        alignItems: 'center',
        width: '100%',
    },
    secaoEdicao: {
        width: '100%',
    },
    nomePerfil: {
        color: '#bfc0d1',
        fontSize: 22,
        fontWeight: 'bold',
        marginBottom: 5,
        textAlign: 'center',
        fontFamily: 'Roboto-Bold',
    },
    emailPerfil: {
        color: '#9ca3af',
        fontSize: 14,
        marginBottom: 10,
        textAlign: 'center',
        fontFamily: 'Roboto-Regular',
    },
    bioPerfil: {
        color: '#bfc0d1',
        fontSize: 14,
        textAlign: 'center',
        marginVertical: 10,
        fontStyle: 'italic',
        fontFamily: 'Roboto-Regular',
    },
    inputPerfil: {
        borderWidth: 1,
        borderColor: '#60519b',
        backgroundColor: '#0c101c',
        borderRadius: 8,
        marginVertical: 10,
        paddingHorizontal: 15,
        paddingVertical: 12,
        color: '#bfc0d1',
        fontSize: 16,
        fontFamily: 'Roboto-Regular',
    },
    labelInput: {
        color: '#bfc0d1',
        fontSize: 14,
        fontWeight: '600',
        marginTop: 10,
        marginBottom: 5,
        fontFamily: 'Roboto-Medium',
    },
    botoesEdicao: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 15,
        width: '100%',
    },
    botaoSalvar: {
        backgroundColor: '#60519b',
        borderColor: '#836fd1',
    },
    botaoCancelar: {
        backgroundColor: '#444',
        borderColor: '#666',
    },
    gridEstatisticas: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        marginHorizontal: 10,
        marginVertical: 15,
    },
    cardEstatistica: {
        backgroundColor: '#212636',
        borderWidth: 1,
        borderColor: '#2e354d',
        borderRadius: 12,
        paddingHorizontal: 20,
        paddingVertical: 20,
        width: '48%',
        marginVertical: 8,
        alignItems: 'center',
    },
    numeroEstatistica: {
        color: '#bfc0d1',
        fontSize: 28,
        fontWeight: 'bold',
        marginVertical: 8,
        fontFamily: 'Roboto-Bold',
    },
    labelEstatistica: {
        color: '#9ca3af',
        fontSize: 12,
        fontWeight: '600',
        fontFamily: 'Roboto-Medium',
    },
    itemProgresso: {
        paddingVertical: 15,
        paddingHorizontal: 10,
    },
    itemProgressoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    itemProgressoTitulo: {
        color: '#bfc0d1',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 12,
        fontFamily: 'Roboto-Medium',
    },
    itemProgressoValor: {
        color: '#60519b',
        fontSize: 20,
        fontWeight: 'bold',
        marginLeft: 32,
        fontFamily: 'Roboto-Bold',
    },
    separador: {
        height: 1,
        backgroundColor: '#2e354d',
        marginVertical: 0,
    },
    cardPreferencias: {
        backgroundColor: '#212636',
        borderWidth: 1,
        borderColor: '#2e354d',
        borderRadius: 12,
        marginHorizontal: 10,
        marginVertical: 15,
        overflow: 'hidden',
    },
    itemPreferencia: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 15,
        paddingVertical: 15,
    },
    itemPreferenciaContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    itemPreferenciaTexto: {
        color: '#bfc0d1',
        fontSize: 16,
        fontWeight: '500',
        marginLeft: 12,
        fontFamily: 'Roboto-Medium',
    },
    botaoLogout: {
        backgroundColor: '#8b0000',
        borderColor: '#ff0000',
        width: '70%',
    },
    secaoFixaMissoes: {
        backgroundColor: '#1c202c',
        paddingHorizontal: 10,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#2e354d',
    },
    filtrosContainerMissoes: {
        marginHorizontal: -10,
        marginBottom: 0,
        maxHeight: 50,
        paddingHorizontal: 10,
    },
    botaoFiltroMissoes: {
        borderWidth: 1,
        borderColor: '#60519b',
        backgroundColor: 'transparent',
        borderRadius: 20,
        paddingHorizontal: 15,
        paddingVertical: 8,
        marginRight: 10,
    },
    botaoFiltroMissoesAtivo: {
        backgroundColor: '#60519b',
        borderColor: '#836fd1',
    },
    textoBotaoFiltroMissoes: {
        color: '#bfc0d1',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Roboto-Medium',
    },
    textoBotaoFiltroMissoesAtivo: {
        color: '#fff',
    },
    secaoScrollMissoes: {
        flex: 1,
        backgroundColor: '#1c202c',
        paddingHorizontal: 10,
    },
    cardMissao: {
        borderWidth: 2,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        marginHorizontal: 0,
        marginVertical: 8,
    },
    missaoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    missaoTitulo: {
        color: '#bfc0d1',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 4,
        fontFamily: 'Roboto-Bold',
    },
    missaoDescricao: {
        color: '#9ca3af',
        fontSize: 12,
        lineHeight: 16,
        fontFamily: 'Roboto-Regular',
    },
    badgeDificuldade: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        borderWidth: 1,
        marginLeft: 10,
    },
    textoBadgeDificuldade: {
        fontSize: 12,
        fontWeight: 'bold',
        fontFamily: 'Roboto-Bold',
    },
    barraFundoMissao: {
        height: 14,
        width: '100%',
        backgroundColor: '#1a1f2e',
        borderRadius: 8,
        overflow: 'hidden',
        marginVertical: 8,
        borderWidth: 1,
        borderColor: '#2e354d',
    },
    barraPreenchidaMissao: {
        height: '100%',
        borderRadius: 6,
    },
    textoPorcentagemMissao: {
        fontSize: 11,
        color: '#9ca3af',
        marginBottom: 10,
        fontFamily: 'Roboto-Regular',
    },
    recompensasContainer: {
        marginVertical: 10,
    },
    recompensasLabel: {
        color: '#bfc0d1',
        fontSize: 12,
        fontWeight: 'bold',
        marginBottom: 6,
        fontFamily: 'Roboto-Bold',
    },
    recompensasGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
    },
    recompensaItem: {
        alignItems: 'center',
        marginRight: 12,
        marginBottom: 6,
    },
    recompensaIconContainer: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: '#1a1f2e',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 4,
        borderWidth: 1,
        borderColor: '#2e354d',
    },
    recompensaNome: {
        color: '#bfc0d1',
        fontSize: 10,
        fontWeight: '600',
        textAlign: 'center',
        maxWidth: 45,
        fontFamily: 'Roboto-Medium',
    },
    botaoConcluido: {
        backgroundColor: '#4caf50',
        borderColor: '#81c784',
        marginTop: 10,
        width: '70%',
    },
    botaoEmProgresso: {
        backgroundColor: '#666',
        borderColor: '#999',
        marginTop: 10,
        width: '70%',
        opacity: 0.7,
    },
    // ========== ESTILOS PARA O JOGO ==========
    gameCanvas: {
        backgroundColor: '#1a1f2e',
        borderWidth: 2,
        borderColor: '#2e354d',
        borderRadius: 12,
        position: 'relative',
        overflow: 'hidden',
    },
    gameObject: {
        position: 'absolute',
        backgroundColor: '#212636',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    gameObjectLabel: {
        color: '#bfc0d1',
        fontSize: 10,
        fontWeight: 'bold',
        marginTop: 4,
        textAlign: 'center',
        fontFamily: 'Roboto-Bold',
    },
    character: {
        position: 'absolute',
        backgroundColor: '#1a1f2e',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#60519b',
    },
    gameInfoPanel: {
        backgroundColor: '#212636',
        borderTopWidth: 1,
        borderTopColor: '#2e354d',
        paddingHorizontal: 15,
        paddingVertical: 15,
        marginHorizontal: 10,
        marginTop: 10,
        borderRadius: 12,
        minHeight: 100,
    },
    objectSelectionPanel: {
        width: '100%',
    },
    objectSelectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    objectSelectionTitle: {
        color: '#bfc0d1',
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 12,
        flex: 1,
        fontFamily: 'Roboto-Bold',
    },
    objectSelectionType: {
        color: '#9ca3af',
        fontSize: 12,
        marginBottom: 12,
        fontFamily: 'Roboto-Regular',
    },
    objectActionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 10,
    },
    botaoCustomize: {
        backgroundColor: '#7c1272',
        borderColor: '#836fd1',
        width: '45%',
        maxWidth: 150,
    },
    botaoUse: {
        backgroundColor: '#4caf50',
        borderColor: '#81c784',
        width: '45%',
        maxWidth: 150,
    },
    gameStatusPanel: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    gameStatusText: {
        color: '#bfc0d1',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 10,
        fontFamily: 'Roboto-Regular',
    },
    // ========== ESTILOS NOVOS — PERFIL (Firebase) ==========
    nomeUsuario: {
        color: '#bfc0d1',
        fontSize: 22,
        fontWeight: 'bold',
        marginBottom: 4,
        textAlign: 'center',
        fontFamily: 'Roboto-Bold',
    },
    emailUsuario: {
        color: '#9ca3af',
        fontSize: 14,
        marginBottom: 8,
        textAlign: 'center',
        fontFamily: 'Roboto-Regular',
    },
    bioUsuario: {
        color: '#bfc0d1',
        fontSize: 14,
        textAlign: 'center',
        marginVertical: 8,
        fontStyle: 'italic',
        fontFamily: 'Roboto-Regular',
    },
    botaoEditar: {
        backgroundColor: '#60519b',
        borderWidth: 1,
        borderColor: '#836fd1',
        borderRadius: 8,
        paddingHorizontal: 20,
        paddingVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
    },
    textoBotaoEditar: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Roboto-Medium',
    },
    secaoEstatisticas: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        backgroundColor: '#212636',
        borderWidth: 1,
        borderColor: '#2e354d',
        borderRadius: 12,
        marginHorizontal: 10,
        marginVertical: 8,
        paddingVertical: 15,
        paddingHorizontal: 10,
    },
    estatisticaItem: {
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        minWidth: 60,
    },
    estatisticaValor: {
        color: '#bfc0d1',
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'Roboto-Bold',
        marginBottom: 4,
    },
    estatisticaLabel: {
        color: '#9ca3af',
        fontSize: 11,
        fontWeight: '600',
        fontFamily: 'Roboto-Medium',
        textAlign: 'center',
    },
    botaoAcao: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#212636',
        borderWidth: 1,
        borderColor: '#2e354d',
        borderRadius: 10,
        paddingHorizontal: 15,
        paddingVertical: 14,
        gap: 12,
    },
    textoBotaoAcao: {
        color: '#bfc0d1',
        fontSize: 15,
        fontWeight: '500',
        fontFamily: 'Roboto-Medium',
        flex: 1,
    },
});

export default conteudoStyle;
