import { Dimensions, StyleSheet } from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const mascara = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#1c202c',
    margin: 0,
    padding: 0,
    zIndex: 0,
    width: windowWidth,
    height: windowHeight,
    fontFamily: 'Roboto-Regular',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#bfc0d1',
  },
  logo: {
    width: 300,
    height: 300,
    backgroundColor: 'transparent',
    resizeMode: 'contain',
    alignSelf: 'center',
    marginVertical: 5,
  },
  inputTexto: {
    borderWidth: 1,
    width: "80%",
    maxWidth: 400,
    borderColor: '#60519b',
    backgroundColor: '#0c101c',
    borderRadius: 5,
    margin: 5,
    padding: 10,
    alignSelf: "center",
    color: '#bfc0d1',
    fontFamily: 'Roboto-Regular',
  },
  botao: {
    width: "60%",
    maxWidth: 200,
    borderWidth: 1,
    borderColor: '#bfc0d1',
    backgroundColor: '#60519b',
    borderRadius: 5,
    margin: 5,
    padding: 10,
    alignSelf: "center",
    fontFamily: 'Roboto-Regular',
  },
  textoBotao: {
    color: "#ddd",
    fontWeight: "bold",
    alignSelf: "center",
    fontFamily: 'Roboto-Regular',
  },
  botaoPressionado: {
    backgroundColor: "#7061ab",
    transform: [{ scale: 0.96 }]
  },
  cxTituloLogin: {
    borderBottomWidth: 2,
    borderColor: '#bfc0d1',
    margin: 0,
    padding: 0,
    alignSelf: "center",
    width: "95%",
    backgroundColor: "#2f2146",
    fontFamily: 'Roboto-Regular',
  },
  cxLogin: {
    borderWidth: 1,
    borderColor: '#bfc0d1',
    margin: 0,
    padding: 5,
    width: '90%',
    maxWidth: 475,
    alignSelf: 'center',
    borderRadius: 5,
    backgroundColor: "#2f2146",
    fontFamily: 'Roboto-Regular',
  },
  cxInput: {
    paddingTop: 15,
    paddingBottom: 15,
    backgroundColor: "#1b1723",
  },
  imgFundo: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    zIndex: -1,
    resizeMode: 'cover',
  },
  abaMenu: {
    margin: 2,
    marginBottom: 8,
    paddingHorizontal: 6,
    paddingVertical: 6,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 58,
    minHeight: 58,
    maxWidth: 76,
    maxHeight: 72,
  },
  abaMenuTexto: {
    color: '#bfc0d1',
    fontSize: 10,
    fontFamily: 'Roboto-Medium',
    marginTop: 3,
    textAlign: 'center',
  },
  abaPressionada: {
    backgroundColor: "#3d2a5d",
    transform: [{ scale: 0.96 }]
  }
});

export default mascara;
