import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const distDir = join(rootDir, "dist");
const appOutput = resolve(rootDir, "..", "constants", "gameBundleHtml.ts");
const assetsOutput = resolve(rootDir, "..", "constants", "gameAssetMap.ts");

function readDistFile(relativePath) {
  return readFileSync(join(distDir, relativePath), "utf8");
}

function mimeType(filePath) {
  if (filePath.endsWith(".svg")) return "image/svg+xml";
  if (filePath.endsWith(".png")) return "image/png";
  if (filePath.endsWith(".jpg") || filePath.endsWith(".jpeg")) return "image/jpeg";
  if (filePath.endsWith(".json")) return "application/json";
  return "application/octet-stream";
}

function toDataUri(relativePath) {
  const absolutePath = join(rootDir, "public", relativePath);
  if (!existsSync(absolutePath)) return relativePath;
  const data = readFileSync(absolutePath);
  return `data:${mimeType(relativePath)};base64,${data.toString("base64")}`;
}

function escapeTemplate(value) {
  return value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

let html = readDistFile("index.html");

html = html.replace(/<link rel="stylesheet" crossorigin href="\.\/([^"]+)">/g, (_, cssPath) => {
  const css = readDistFile(cssPath);
  return `<style>${css}</style>`;
});

html = html.replace(/<script type="module" crossorigin src="\.\/([^"]+)"><\/script>/g, (_, jsPath) => {
  let js = readDistFile(jsPath);
  const assetPaths = Array.from(js.matchAll(/assets\/[a-zA-Z0-9_./-]+\.(svg|png|jpg|jpeg|json)/g)).map((match) => match[0]);
  for (const assetPath of new Set(assetPaths)) {
    js = js.split(assetPath).join(toDataUri(assetPath));
  }
  return `<script>${js}</script>`;
});

const ts = `/* This file is generated by game_folder/scripts/embed-game.mjs. */\nexport const GAME_HTML = \`${escapeTemplate(html)}\`;\n`;

mkdirSync(dirname(appOutput), { recursive: true });
writeFileSync(appOutput, ts, "utf8");
const publicAssetsDir = join(rootDir, "public", "assets");
const assetMap = {};
function walk(dir, relativeBase) {
  for (const entry of readdirSync(dir)) {
    const absolutePath = join(dir, entry);
    const relativePath = relativeBase ? `${relativeBase}/${entry}` : entry;
    if (statSync(absolutePath).isDirectory()) {
      walk(absolutePath, relativePath);
    } else {
      const key = `assets/${relativePath.replace(/\\/g, "/")}`;
      assetMap[key] = toDataUri(key);
    }
  }
}
walk(publicAssetsDir, "");
const assetsTs = `/* This file is generated by game_folder/scripts/embed-game.mjs. */\nexport const GAME_ASSETS = ${JSON.stringify(assetMap)} as const;\n`;
writeFileSync(assetsOutput, assetsTs, "utf8");
console.log(`Generated ${appOutput}`);
console.log(`Generated ${assetsOutput}`);
